# Changes here will be overwritten by Copier
_commit: 1.2.0
_src_path: gh:mkdocstrings/handler-template
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2023'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC License
insiders: true
insiders_email: insiders@pawamoy.fr
insiders_repository_name: mkdocstrings-shell
language: Shell
project_description: A shell scripts/libraries handler for mkdocstrings.
project_name: mkdocstrings-shell
public_release: true
python_package_distribution_name: mkdocstrings-shell
python_package_import_name: shell
repository_name: shell
repository_namespace: mkdocstrings
repository_provider: github.com

